// // This theme was made for FlexColorScheme version 6.1.1. Make sure
// // you use same or higher version, but still same major version. If
// // you use a lower version, some properties may not be supported. In
// // that case you can also remove them after copying the theme to your app.
// theme: FlexThemeData.light(
//   scheme: FlexScheme.verdunHemlock,
//   surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
//   blendLevel: 9,
//   tabBarStyle: FlexTabBarStyle.universal,
//   subThemesData: const FlexSubThemesData(
//     blendOnLevel: 10,
//     blendOnColors: false,
//     useFlutterDefaults: true,
//     thinBorderWidth: 1.0,
//     defaultRadius: 7.0,
//     textButtonRadius: 11.0,
//     elevatedButtonRadius: 22.0,
//     outlinedButtonRadius: 23.0,
//     outlinedButtonOutlineSchemeColor: SchemeColor.primary,
//     outlinedButtonBorderWidth: 2.0,
//     outlinedButtonPressedBorderWidth: 2.0,
//     toggleButtonsRadius: 17.0,
//     inputDecoratorRadius: 33.0,
//     inputDecoratorUnfocusedHasBorder: false,
//     inputDecoratorFocusedBorderWidth: 2.5,
//     fabSchemeColor: SchemeColor.primary,
//     chipSelectedSchemeColor: SchemeColor.onPrimary,
//     chipDeleteIconSchemeColor: SchemeColor.primary,
//     chipRadius: 4.0,
//     cardRadius: 22.0,
//     popupMenuRadius: 2.0,
//     popupMenuElevation: 6.0,
//     popupMenuSchemeColor: SchemeColor.onPrimary,
//     popupMenuOpacity: 0.99,
//   ),
//   visualDensity: FlexColorScheme.comfortablePlatformDensity,
//   useMaterial3: true,
//   swapLegacyOnMaterial3: true,
//   // To use the playground font, add GoogleFonts package and uncomment
//   // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// darkTheme: FlexThemeData.dark(
//   scheme: FlexScheme.verdunHemlock,
//   surfaceMode: FlexSurfaceMode.highSurfaceLowScaffold,
//   blendLevel: 22,
//   tabBarStyle: FlexTabBarStyle.universal,
//   darkIsTrueBlack: true,
//   subThemesData: const FlexSubThemesData(
//     blendOnLevel: 40,
//     useFlutterDefaults: true,
//     defaultRadius: 7.0,
//     thinBorderWidth: 1.0,
//     textButtonRadius: 11.0,
//     elevatedButtonRadius: 22.0,
//     outlinedButtonRadius: 23.0,
//     outlinedButtonOutlineSchemeColor: SchemeColor.primary,
//     outlinedButtonBorderWidth: 2.0,
//     outlinedButtonPressedBorderWidth: 2.0,
//     toggleButtonsRadius: 17.0,
//     inputDecoratorRadius: 33.0,
//     inputDecoratorUnfocusedHasBorder: false,
//     inputDecoratorFocusedBorderWidth: 2.5,
//     fabSchemeColor: SchemeColor.primary,
//     chipSelectedSchemeColor: SchemeColor.onPrimary,
//     chipDeleteIconSchemeColor: SchemeColor.primary,
//     chipRadius: 4.0,
//     cardRadius: 22.0,
//     popupMenuRadius: 2.0,
//     popupMenuElevation: 6.0,
//     popupMenuSchemeColor: SchemeColor.onPrimary,
//     popupMenuOpacity: 0.99,
//   ),
//   visualDensity: FlexColorScheme.comfortablePlatformDensity,
//   useMaterial3: true,
//   swapLegacyOnMaterial3: true,
//   // To use the Playground font, add GoogleFonts package and uncomment
//   // fontFamily: GoogleFonts.notoSans().fontFamily,
// ),
// // If you do not have a themeMode switch, uncomment this line
// // to let the device system mode control the theme mode:
// // themeMode: ThemeMode.system,
