// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDphgF6MlWdGfz5aUfZh4aJ6ScWAOqITA',
    appId: '1:182743752167:web:ac7f70fbba85bc0b12f142',
    messagingSenderId: '182743752167',
    projectId: 'digitendance-dev',
    authDomain: 'digitendance-dev.firebaseapp.com',
    storageBucket: 'digitendance-dev.appspot.com',
    measurementId: 'G-QRQFPV0D41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAR2GD_3nKliX9tyXvQQ8_nqXw2KJ1RaY',
    appId: '1:182743752167:android:9319470cbcdc338612f142',
    messagingSenderId: '182743752167',
    projectId: 'digitendance-dev',
    storageBucket: 'digitendance-dev.appspot.com',
  );
}
